import { writeFile } from "node:fs/promises"
import path from "node:path"
import type { RunReport } from "./types.js"

/**
 * Phase 4 of the plan of action calls for opening a PR automatically. This
 * repo does not do that, and reads no GITHUB_TOKEN — see README. `renderPrBody`
 * produces the exact markdown a real integration would attach to the PR;
 * `publishPr` is the documented seam where the GitHub API call would go instead
 * of the local file write it does today.
 */
export function renderPrBody(report: RunReport): string {
  const { reproduction, patch, sandbox, reverify } = report
  const lines: string[] = []

  lines.push(`## ${patch.description || "candidate patch"}`)
  lines.push("")
  lines.push(`**Run:** \`${report.runId}\` (${report.mode} mode) — status: **${report.status}**`)
  lines.push("")

  lines.push("### Reproduction")
  lines.push(`- Backend: ${reproduction.backend}`)
  lines.push(`- Target: ${reproduction.targetUrl}`)
  lines.push(`- Reproduced: ${reproduction.reproduced ? "yes" : "no"}`)
  if (reproduction.pageErrors.length) {
    lines.push("- Page errors:")
    for (const e of reproduction.pageErrors) lines.push(`  - \`${e}\``)
  }
  lines.push(
    reproduction.replay.requested
      ? reproduction.replay.available
        ? `- Session replay: recorded (\`${reproduction.sessionId}\`)`
        : `- Session replay: not confirmed — ${reproduction.replay.note}`
      : `- Session replay: not requested — ${reproduction.replay.note}`,
  )
  lines.push("")

  lines.push("### Patch")
  lines.push("```diff")
  lines.push((patch.diff || "(no diff generated)").trimEnd())
  lines.push("```")
  lines.push("")

  lines.push("### Sandbox verification")
  lines.push(`- Backend: ${sandbox.backend} (\`${sandbox.sandboxId || "n/a"}\`)`)
  lines.push(`- Patch applied: ${sandbox.applied ? "yes" : `no — ${sandbox.applyError ?? "unknown error"}`}`)
  lines.push(`- Test exit code: ${sandbox.testExitCode ?? "n/a"}`)
  lines.push(`- Passed: ${sandbox.passed ? "yes" : "no"}`)
  lines.push("")

  lines.push("### Re-verification")
  if (reverify.attempted) {
    lines.push(`- Passed: ${reverify.passed ? "yes" : "no"}`)
    if (reverify.renderedText !== null) lines.push(`- Rendered: \`${reverify.renderedText}\``)
    if (reverify.pageErrors.length) {
      lines.push("- Page errors:")
      for (const e of reverify.pageErrors) lines.push(`  - \`${e}\``)
    }
  } else {
    lines.push(`- Not attempted: ${reverify.note}`)
  }
  lines.push("")

  lines.push("---")
  lines.push("_Generated by retrace. Not opened automatically — see `src/pr.ts`._")
  return lines.join("\n")
}

/**
 * NOT IMPLEMENTED as a real GitHub call. A production integration would push a
 * branch carrying `patch.diff`, then POST to
 * `https://api.github.com/repos/{owner}/{repo}/pulls` with
 * `body: renderPrBody(report)`, using a `GITHUB_TOKEN` this application never
 * reads. Rather than claim success it never earns, this writes the same body
 * to disk so the artifact is still complete and inspectable.
 */
export async function publishPr(report: RunReport, artifactsDir: string): Promise<{ published: false; bodyPath: string }> {
  const bodyPath = path.join(artifactsDir, "pr-body.md")
  await writeFile(bodyPath, renderPrBody(report), "utf8")
  return { published: false, bodyPath }
}
